services:
  # PostgreSQL Database
  - type: pg
    name: farm-management-db
    plan: starter
    databaseName: farm_management
    user: postgres

  # Redis Cache
  - type: redis
    name: farm-management-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Django Web Application
  - type: web
    name: farm-management-web
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: farm_management.settings_production
      - key: DB_NAME
        fromService:
          type: pg
          name: farm-management-db
          property: database
      - key: DB_USER
        fromService:
          type: pg
          name: farm-management-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pg
          name: farm-management-db
          property: password
      - key: DB_HOST
        fromService:
          type: pg
          name: farm-management-db
          property: host
      - key: DB_PORT
        fromService:
          type: pg
          name: farm-management-db
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: farm-management-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-management-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-management-redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.onrender.com,http://localhost:3000"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: FRONTEND_URL
        value: "https://your-frontend-app.onrender.com"
    healthCheckPath: /api/health/