# Generated by Django 5.0.1 on 2026-01-20 09:32

import vendors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_add_unique_gstin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gstin_number',
            field=models.CharField(blank=True, help_text='15-digit GSTIN number', max_length=15, null=True, unique=True, validators=[vendors.validators.validate_gstin], verbose_name='GSTIN Number'),
        ),
    ]
