# Generated by Django 5.0.1 on 2026-01-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0018_add_crop_variety_to_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='plant_age',
            field=models.CharField(blank=True, choices=[('0_2', '0-2 years'), ('2_3', '2-3 years'), ('above_3', 'Above 3 years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='variety_subtype',
            field=models.CharField(blank=True, choices=[('wine_grapes', 'Wine Grapes'), ('table_grapes', 'Table Grapes')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='variety_timing',
            field=models.CharField(blank=True, choices=[('early', 'Early'), ('late', 'Late')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='variety_type',
            field=models.CharField(blank=True, choices=[('pre_season', 'Pre-season'), ('seasonal', 'Seasonal')], max_length=20, null=True),
        ),
    ]
