# Generated by Django 5.0.1 on 2026-01-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0020_farmirrigation_foundation_pruning_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='emitters_per_plant',
            field=models.IntegerField(blank=True, help_text='Number of emitters per plant (Grapes drip irrigation)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='flow_rate_liter_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flow rate in liters/hour (Grapes drip irrigation)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='foundation_pruning_date',
            field=models.DateField(blank=True, help_text='Foundation pruning date (Grapes only)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='fruit_pruning_date',
            field=models.DateField(blank=True, help_text='Fruit pruning date (Grapes only)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='last_harvesting_date',
            field=models.DateField(blank=True, help_text='Last harvesting date (Grapes only)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='plant_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plant spacing in meters (Grapes drip irrigation)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='resting_period_days',
            field=models.IntegerField(blank=True, help_text='Resting period in days (Grapes only)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='row_spacing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Row spacing in meters (Grapes drip irrigation)', max_digits=8, null=True),
        ),
    ]
