# Generated by Django 5.0.1 on 2026-01-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0021_farm_emitters_per_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmirrigation',
            name='foundation_pruning_date',
        ),
        migrations.RemoveField(
            model_name='farmirrigation',
            name='fruit_pruning_date',
        ),
        migrations.RemoveField(
            model_name='farmirrigation',
            name='last_harvesting_date',
        ),
        migrations.RemoveField(
            model_name='farmirrigation',
            name='plantation_date',
        ),
    ]
