# Generated by Django 5.0.1 on 2026-02-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0022_remove_farmirrigation_foundation_pruning_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='grapes_plantation_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('wine', 'Wine Grapes'), ('table', 'Table Grapes'), ('late', 'Late'), ('early', 'Early'), ('pre_season', 'Pre-Season'), ('seasonal', 'Seasonal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='sugarcane_plantation_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('adsali', 'Adsali'), ('suru', 'Suru'), ('ratoon', 'Ratoon'), ('pre-seasonal', 'Pre-Seasonal'), ('post-seasonal', 'Post-Seasonal'), ('pre_seasonal', 'Pre-Seasonal'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='sugarcane_planting_method',
            field=models.CharField(blank=True, choices=[('', '---------'), ('3_bud', '3 Bud Method'), ('2_bud', '2 Bud Method'), ('1_bud', '1 Bud Method'), ('1_bud_stip_Method', '1 Bud (stip Method)'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
