# Generated by Django 5.0.1 on 2026-02-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0023_farm_grapes_plantation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapesReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('residue', 'Residue Analysis'), ('variety', 'Variety Identification'), ('soil', 'Soil Report')], max_length=20)),
                ('file', models.FileField(upload_to='grapes_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
