# Generated by Django 5.0.1 on 2026-02-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0024_grapesreports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrapesReports',
        ),
    ]
